/*
 * Copyright (C) 2021 Martin Mandelkow <mandelkow@apotheke-schwerin.de>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package com.apothekeammarienplatz.apothekenarchiv;

import javax.swing.JDialog;
import javax.swing.JLabel;

/**
 *
 * @author Martin Mandelkow <mandelkow@apotheke-schwerin.de>
 */
public class PlausibilitätsArchiv extends javax.swing.JPanel {

    /**
     * Creates new form PlausibilitätsArchiv
     */
    public PlausibilitätsArchiv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        plausiNummernTextField = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        copyEncryptedCheckBox = new javax.swing.JCheckBox();
        resultLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        jLabel1.setText("Plausibilitätsprotokolle werden archiviert, rechtssicher signiert und in die Versionskontrolle aufgenommen.");

        plausiNummernTextField.setColumns(7);
        try {
            plausiNummernTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        plausiNummernTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        plausiNummernTextField.setToolTipText("Jahr - laufende Nummer");
        plausiNummernTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plausiNummernTextFieldActionPerformed(evt);
            }
        });
        plausiNummernTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                plausiNummernTextFieldKeyTyped(evt);
            }
        });

        jLabel2.setText("Plausi Nummer");

        copyEncryptedCheckBox.setText("zusätzlich verschlüsselt speichern");
        copyEncryptedCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyEncryptedCheckBoxActionPerformed(evt);
            }
        });

        resultLabel.setText("...");

        startButton.setText("StartText");
        startButton.setActionCommand("StartCommand");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("EndeText");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(plausiNummernTextField)
                                    .addComponent(copyEncryptedCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plausiNummernTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(copyEncryptedCheckBox)
                .addGap(18, 18, 18)
                .addComponent(resultLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(cancelButton))
                .addContainerGap(141, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        String plausiNummer = (String) plausiNummernTextField.getValue();
        boolean copyEncrypted = copyEncryptedCheckBox.isSelected();
        String fileNameString;
        fileNameString = plausiNummer + ".pdf";
        System.out.println("fileNameString:");
        System.out.println(fileNameString);
        System.out.println("Versuche zu scannen:");
        ScannerWrapper scannerWrapper = new ScannerWrapper(fileNameString);
        System.out.println(scannerWrapper.getCommandOutput());
        System.out.println("Versuche zu signieren:");
        CryptoWrapper cryptoWrapper = new CryptoWrapper(fileNameString, copyEncrypted);
        System.out.println(cryptoWrapper.getCommandOutput());
        // Erzeugung eines neuen Frames mit
        // dem Titel Beispiel JDialog
        JDialog meinJDialog = new JDialog();
        // Titel wird gesetzt
        meinJDialog.setTitle("Mein JDialog Beispiel");
        // Breite und Höhe des Fensters werden
        // auf 200 Pixel gesetzt
        meinJDialog.setSize(200, 200);
        // Dialog wird auf modal gesetzt
        meinJDialog.setModal(true);
        // Hinzufügen einer Komponente,
        // in diesem Fall ein JLabel
        meinJDialog.add(new JLabel("Hier funktioniert noch nichts."));
        // Wir lassen unseren Dialog anzeigen
        meinJDialog.setVisible(true);
    }//GEN-LAST:event_startButtonActionPerformed

    private void copyEncryptedCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyEncryptedCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_copyEncryptedCheckBoxActionPerformed

    private void plausiNummernTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plausiNummernTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plausiNummernTextFieldActionPerformed

    private void plausiNummernTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_plausiNummernTextFieldKeyTyped
        System.out.println(evt.getKeyChar());
        System.out.println(plausiNummernTextField.getText());
    }//GEN-LAST:event_plausiNummernTextFieldKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox copyEncryptedCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JFormattedTextField plausiNummernTextField;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
